name: Deploy Web to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/web-deploy.yml"
      - "apps/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn

      - name: Build @notely/v1
        working-directory: ./apps/v1
        run: yarn build

      - name: Build @notely/v2
        working-directory: ./apps/v2
        run: yarn build

      - name: Export @notely/v2
        working-directory: ./apps/v2
        run: yarn export

      - name: Move all projects into a common folder to deploy
        working-directory: ./apps
        run: |
          mkdir gh-pages
          cp -r ./v2/dist/* ./gh-pages
          cp -r ./v1/dist/* ./gh-pages/old

      - name: Add .nojekyll file
        working-directory: ./apps
        run: touch ./gh-pages/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./apps/gh-pages
